spring:
  application:
    name: notification-service

  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      username: 'nacos'
      password: 'nacos'

  config:
    import:
      - nacos:notificationservice-config.yaml?refreshEnabled=true&group=CHAI_GROUPING
      - nacos:consts.yaml?refreshEnabled=true&group=CHAI_GROUPING
