allowed-routes: /swagger-ui/**,/v3/api-docs/**,/api/auth/**

jwt:
  secret: wohenshenmiwohenshenmi114514chaigroupingwohenshenmiwohenshenmi1919810
  expiration: 360000000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chai_grouping?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jackson:
    property-naming-strategy: SNAKE_CASE
