spring:
  application:
    name: group-service

  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      username: 'nacos'
      password: 'nacos'

  config:
    import:
      - nacos:groupservice-config.yaml?refreshEnabled=true&group=CHAI_GROUPING
      - nacos:consts.yaml?refreshEnabled=true&group=CHAI_GROUPING

mybatis-plus:
  mapper-locations: classpath:/common-utils/**/*.xml